Repository discos/srt-single-dish-tools, pull requests merged in 2025-03, with the labels that each got.

#256 Fix #255, enhanced the SDTmonitor web page
  docs/changes/256.feature.rst
  srttools/monitor/webserver.py
Labels: enhancement

#251 Eliminate deprecated test runner
  srttools/_astropy_init.py
Labels: no-changelog-entry-needed

#268 Fix #267, used absolute paths in `os.path.commonpath`
  docs/changes/268.bugfix.rst
  srttools/scan.py
  srttools/tests/test_io_and_scan.py
Labels: bug
